# -*- coding: utf-8 -*-
"""KODESIC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_PMaivm13OQPaUoKkUZZAKBJlQZWvmgO
"""

import pandas as pd
import numpy as np
import folium
from sklearn.cluster import KMeans

from sklearn.preprocessing import StandardScaler
from google.colab import files
import io

pd.read_excel('/content/Dataset_RekapDBD_Tunggal Dara.xlsx')
df = pd.read_excel('/content/Dataset_RekapDBD_Tunggal Dara.xlsx', skiprows=2)
df.head(10)

df = df.drop('Unnamed: 0', axis=1)
df.head()

new_column_names = [
    'wilayah', 'jml penduduk',
    'jan p', 'jan m', 'feb p', 'feb m', 'mar p', 'mar m',
    'apr p', 'apr m', 'mei p', 'mei m', 'jun p', 'jun m',
    'jul p', 'jul m', 'agt p', 'agt m', 'sep p', 'sep m',
    'okt p', 'okt m', 'nov p', 'nov m', 'des p', 'des m',
    'jml p', 'jml m', 'ir/100000', 'cfr'
]

df.columns = new_column_names

display(df.head())

df.tail()

df = df.drop(index=16).reset_index(drop=True)
print('hapus row NaN')
df.tail()

df.info()

months = ['jan', 'feb', 'mar', 'apr', 'mei', 'jun', 'jul', 'agt', 'sep', 'okt', 'nov', 'des']

monthly_p_cases = []
monthly_m_cases = []

for month in months:
    p_col = f'{month} p'
    m_col = f'{month} m'
    monthly_p_cases.append(df[p_col].sum())
    monthly_m_cases.append(df[m_col].sum())

monthly_summary_df = pd.DataFrame({
    'Bulan': months,
    'Total P': monthly_p_cases,
    'Total M': monthly_m_cases
})

display(monthly_summary_df)

total_p_cases = df['jml p'].sum()
total_m_cases = df['jml m'].sum()

print(f"Total Positive Cases: {total_p_cases}")
print(f"Total Mortality Cases: {total_m_cases}")



from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

features = ['jml p', 'jml m', 'jml penduduk', 'ir/100000', 'cfr']
X = df[features]

print("Selected features for clustering:")
display(X.head())

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print("Features scaled successfully. Displaying the first 5 rows of scaled data:")
display(pd.DataFrame(X_scaled, columns=features).head())

inertia = []
k_range = range(1, 11)

for k in k_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(10, 6))
plt.plot(k_range, inertia, marker='o')
plt.title('Elbow Method for Optimal K')
plt.xlabel('Number of clusters (K)')
plt.ylabel('Inertia')
plt.xticks(k_range)
plt.grid(True)
plt.show()

koordinat_semarang = {
    'mijen': [-7.0601, 110.3168],
    'gunungpati': [-7.1082, 110.3842],
    'banyumanik': [-7.0706, 110.4228],
    'gajah mungkur': [-7.0267, 110.4129],
    'semarang selatan': [-6.9964, 110.4196],
    'semarang barat': [-6.9859, 110.3952],
    'semarang utara': [-6.9631, 110.4262],
    'semarang tengah': [-6.9813, 110.4265],
    'semarang timur': [-6.9745, 110.4418],
    'gayamsari': [-6.9797, 110.4573],
    'genuk': [-6.9616, 110.4801],
    'pedurungan': [-7.0055, 110.4727],
    'tembalang': [-7.0603, 110.4573],
    'candisari': [-7.0163, 110.4300],
    'ngaliyan': [-7.0094, 110.3340],
    'tugu': [-6.9754, 110.3308]
}

# Fungsi untuk mencari koordinat berdasarkan nama wilayah
def get_lat(nama):
    nama_bersih = str(nama).lower().strip() # Ubah ke huruf kecil
    if nama_bersih in koordinat_semarang:
        return koordinat_semarang[nama_bersih][0]
    return None # Jika nama tidak cocok

def get_long(nama):
    nama_bersih = str(nama).lower().strip()
    if nama_bersih in koordinat_semarang:
        return koordinat_semarang[nama_bersih][1]
    return None

# Terapkan ke DataFrame
print("\n[INFO] Mencocokkan nama wilayah dengan koordinat GPS...")
df['Latitude'] = df['wilayah'].apply(get_lat)
df['Longitude'] = df['wilayah'].apply(get_long)

# Cek apakah ada wilayah yang gagal dicocokkan (Typo di Excel?)
data_kosong = df[df['Latitude'].isna()]
if not data_kosong.empty:
    print("\n[PERINGATAN] Ada wilayah yang tidak ditemukan koordinatnya (Cek penulisan di Excel):")
    print(data_kosong['wilayah'].tolist())
    # Isi default agar tidak error (Optional: isi dengan rata-rata Semarang)
    df['Latitude'] = df['Latitude'].fillna(-7.0051)
    df['Longitude'] = df['Longitude'].fillna(110.4381)
else:
    print("[SUKSES] Semua wilayah berhasil dipetakan!")

K = 3
optimal_k = K
kmeans = KMeans(n_clusters=optimal_k, random_state=42, n_init=10)
clusters = kmeans.fit_predict(X_scaled)

df['cluster'] = clusters

print(f'K-Means clustering applied with {optimal_k} clusters.')
display(df.head())

features = ['ir/100000', 'cfr', 'jml p']
X = df[features].fillna(0)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
df['Cluster'] = kmeans.fit_predict(X_scaled)

# Labeling Risiko
summary = df.groupby('Cluster')[features].mean().sort_values(by='ir/100000')
risk_map = {}
labels = ['Risiko Rendah', 'Risiko Sedang', 'Risiko Tinggi (Hotspot)']
for i, c in enumerate(summary.index):
    risk_map[c] = labels[i]
df['Status Risiko'] = df['Cluster'].map(risk_map)

# Tampilkan Data
print("\n--- HASIL ANALISIS ---")
display(df[['wilayah', 'ir/100000', 'Status Risiko', 'Latitude', 'Longitude']].head())

# -----------------------------------------------------------------------------
# VISUALISASI PETA
# -----------------------------------------------------------------------------
colors = {'Risiko Rendah': 'green', 'Risiko Sedang': 'orange', 'Risiko Tinggi (Hotspot)': 'red'}
m = folium.Map(location=[-7.0051, 110.4381], zoom_start=11) # Zoom pas satu kota

for i, row in df.iterrows():
    warna = colors.get(row['Status Risiko'], 'gray')

    popup_html = f"""
    <b>Kec. {row['wilayah'].upper()}</b><br>
    Status: <b>{row['Status Risiko']}</b><br>
    IR: {row['ir/100000']:.2f}<br>
    CFR: {row['cfr']}%
    """

    folium.CircleMarker(
        location=[row['Latitude'], row['Longitude']],
        radius=10 + (row['ir/100000'] * 0.05),
        color=warna,
        fill=True,
        fill_color=warna,
        fill_opacity=0.8,
        popup=folium.Popup(popup_html, max_width=200)
    ).add_to(m)

# Legenda
legend_html = '''
     <div style="position: fixed; bottom: 30px; left: 30px; width: 150px; height: 100px;
     border:2px solid grey; z-index:9999; font-size:14px; background:white; padding: 10px;">
     <b>Legenda</b><br>
     <i style="background:green;width:10px;height:10px;display:inline-block;border-radius:50%"></i> Rendah<br>
     <i style="background:orange;width:10px;height:10px;display:inline-block;border-radius:50%"></i> Sedang<br>
     <i style="background:red;width:10px;height:10px;display:inline-block;border-radius:50%"></i> Tinggi
     </div>
     '''
m.get_root().html.add_child(folium.Element(legend_html))

m

print('Number of wilayah per cluster:')
display(df['cluster'].value_counts().sort_index())

print('\nMean values of features per cluster:')
display(df.groupby('cluster')[features].mean())

plt.figure(figsize=(12, 8))
sns.scatterplot(x='jml penduduk', y='jml p', hue='cluster', data=df, palette='viridis', s=100)
plt.title('Clusters of Wilayah based on Population and Positive Cases')
plt.xlabel('Total Population')
plt.ylabel('Total Positive Cases')
plt.grid(True)
plt.show()